
# Plotly and Cufflinks

Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

## Installation

In order for this all to work, you'll need to install plotly and cufflinks to call plots directly off of a pandas dataframe. These libraries are not currently available through **conda** but are available through **pip**. Install the libraries at your command line/terminal using:

    pip install plotly
    pip install cufflinks

** NOTE: Make sure you only have one installation of Python on your computer when you do this, otherwise the installation may not work. **

## Imports and Set-up

In [ ]:
import pandas as pd
import numpy as np

In [9]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__) # requires version >= 1.9.0

5.24.1

In [17]:
import cufflinks as cf

ModuleNotFoundError: No module named 'cufflinks'

In [ ]:
# For Notebooks
init_notebook_mode(connected=True)

In [19]:
# For offline use
cf.go_offline()

NameError: name 'cf' is not defined

### Fake Data

In [21]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [23]:
df.head()

          A         B         C         D
0  0.270707  0.830145 -1.335683 -0.727566
1  0.139056  0.239869 -0.008915  1.780479
2  0.080263 -0.559009  1.012069  0.754776
3  0.018401  0.686739  0.512722  1.345139
4  0.856855  0.646304  1.172178  0.456075

In [25]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [27]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [29]:
df.iplot(kind='scatter',x='A',y='B',mode='markers',size=10)

AttributeError: 'DataFrame' object has no attribute 'iplot'

## Bar Plots

In [ ]:
df2.iplot(kind='bar',x='Category',y='Values')

In [ ]:
df.count().iplot(kind='bar')

## Boxplots

In [ ]:
df.iplot(kind='box')

## 3d Surface

In [ ]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df3.iplot(kind='surface',colorscale='rdylbu')

## Spread

In [ ]:
df[['A','B']].iplot(kind='spread')

## histogram

In [ ]:
df['A'].iplot(kind='hist',bins=25)

In [ ]:
df.iplot(kind='bubble',x='A',y='B',size='C')

## scatter_matrix()

Similar to sns.pairplot()

In [ ]:
df.scatter_matrix()

# Great Job!